import type { Metadata } from 'next'
import localFont from 'next/font/local'

import './index.css'

const font = localFont({
  src: '../public/fonts/PxPlus_IBM_VGA8.ttf',
  variable: '--font-pxplus'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`font-sans ${font.variable}`}>{children}</body>
    </html>
  )
}
