// TODO: nextjs has a problem with RSC and "dot notation for groups of components" https://github.com/vercel/next.js/issues/75192
import { PopoverRoot, PopoverTrigger, PopoverContent, ArrowSvg } from '@/components/Popover'
import type { PropsWithChildren } from 'react'
import type { Text } from 'hast'
import { nativeReplacement } from './native-replacements'

const LineQuery = ({ children, indentation }: PropsWithChildren<{ indentation: number }>) => (
  <div className="flex">
    <span>{' '.repeat(indentation)}</span>
    <span className="relative mt-[7px] flex flex-col border-2 border-secondary-8 bg-secondary-4 px-2 py-1 leading-[initial] dark:border-secondary-7 dark:bg-secondary-3">
      <div className="absolute top-[-8px] flex translate-x-[2px] rotate-180">
        <ArrowSvg />
      </div>
      {children}
    </span>
  </div>
)

// TODO: proper icons?
const completionIcons = {
  module: 'M',
  class: 'C',
  method: 'M',
  property: 'P',
  constructor: 'C',
  interface: 'I',
  function: 'F',
  string: 'S'
}

type CompletionQuery = {
  completions: Array<{
    kind: 'module' | 'class' | 'method' | 'property' | 'constructor' | 'interface' | 'function' | 'string'
    kindModifiers?: string
    name: string
  }>
  completionsPrefix: string
}

const Completion = ({ queryserialized, nodeserialized }: { queryserialized: string; nodeserialized: string }) => {
  const query: CompletionQuery = JSON.parse(queryserialized) as CompletionQuery
  const node: Text = JSON.parse(nodeserialized) as Text
  const items = query.completions
    .map((i) => {
      const kind = i.kind || 'default'
      const deprecated =
        'kindModifiers' in i &&
        typeof i.kindModifiers === 'string' &&
        i.kindModifiers?.split(',').includes('deprecated')

      const name = i.name
      const parts = [
        name.startsWith(query.completionsPrefix) ? query.completionsPrefix : '',
        name.startsWith(query.completionsPrefix) ? name.slice(query.completionsPrefix.length || 0) : name
      ]

      const icon = completionIcons[kind] ?? completionIcons.property

      return { kind, deprecated, parts, name, icon }
    })
    .map(({ name, icon, deprecated, parts: [matched, unmatched] }) => (
      <li className="inline-flex items-center gap-2 overflow-hidden text-ellipsis whitespace-nowrap text-sm" key={name}>
        {<span className="w-1 text-secondary-9">{icon}</span>}
        <span className={deprecated ? 'line-through opacity-50' : undefined}>
          <span className="text-secondary-11">{matched}</span>
          <span className="text-secondary-10">{unmatched}</span>
        </span>
      </li>
    ))

  return (
    <span>
      {node.value}
      <span className="twoslash-completion-cursor inline-flex flex-col">
        <ul className="twoslash-completion-list relative my-1 inline-flex min-w-40 max-w-80 select-none flex-col whitespace-normal border-2 border-secondary-8 bg-secondary-4 p-2 px-2 py-1 leading-[initial] dark:border-secondary-7 dark:bg-secondary-3">
          {items}
        </ul>
      </span>
    </span>
  )
}

const QueryToken = nativeReplacement('span', 'QueryToken', {
  className: 'underline decoration-primary-11 underline-offset-[4px] decoration-dashed'
})

// TODO: something is lowercasing the tagName property on the hast nodes generated by twoslash, but couldn't figure out where this happens
const codeComponents = {
  Popover: PopoverRoot,
  PopoverContent: PopoverContent,
  PopoverTrigger: PopoverTrigger,
  LineQuery: LineQuery,
  Completion: Completion,
  QueryToken: QueryToken,
  popover: PopoverRoot,
  popovercontent: PopoverContent,
  popovertrigger: PopoverTrigger,
  linequery: LineQuery,
  completion: Completion,
  querytoken: QueryToken
}

export { LineQuery, codeComponents }
